trackedBlocks:
  - CHEST
  - FURNACE
  - BEACON
  - ENCHANTING_TABLE
  - CRAFTING_TABLE
  - BLAST_FURNACE
  - SMOKER
  - LOOM
  - ANVIL
  - CAMPFIRE
  - SOUL_CAMPFIRE
  - BREWING_STAND
  - BEEHIVE
  - BEE_NEST
  - LECTERN
  - ENDER_CHEST
  - BARREL
  - END_PORTAL_FRAME
  - FARMLAND
  - LODESTONE
  - COMPOSTER
  - CAULDRON
  - BELL
  - TRAPPED_CHEST
  - LIGHTNING_ROD
